class CropModel {
  final String name;
  final String category;
  final String growingSeason;
  final double tempMin;
  final double tempMax;
  final double humidityMin;
  final double humidityMax;
  final double rainfallMin;
  final double rainfallMax;
  final String soilType;
  final String waterRequirement;
  final String emoji;

  const CropModel({
    required this.name,
    required this.category,
    required this.growingSeason,
    required this.tempMin,
    required this.tempMax,
    required this.humidityMin,
    required this.humidityMax,
    required this.rainfallMin,
    required this.rainfallMax,
    required this.soilType,
    required this.waterRequirement,
    required this.emoji,
  });

  static const List<CropModel> supportedCrops = [
    // --- Cereals & Grains ---
    CropModel(
      name: "Wheat",
      category: "Cereal Grain",
      growingSeason: "Rabi (Winter)",
      tempMin: 15.0,
      tempMax: 25.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 50.0,
      rainfallMax: 100.0,
      soilType: "Well-drained loam",
      waterRequirement: "Moderate",
      emoji: "🌾",
    ),
    CropModel(
      name: "Rice",
      category: "Cereal Grain",
      growingSeason: "Kharif (Monsoon)",
      tempMin: 22.0,
      tempMax: 32.0,
      humidityMin: 70.0,
      humidityMax: 85.0,
      rainfallMin: 150.0,
      rainfallMax: 300.0,
      soilType: "Clayey alluvial",
      waterRequirement: "High",
      emoji: "🍚",
    ),
    CropModel(
      name: "Maize",
      category: "Cereal / Fodder",
      growingSeason: "Kharif / Spring",
      tempMin: 20.0,
      tempMax: 30.0,
      humidityMin: 55.0,
      humidityMax: 75.0,
      rainfallMin: 60.0,
      rainfallMax: 120.0,
      soilType: "Fertile loam",
      waterRequirement: "Moderate",
      emoji: "🌽",
    ),
    CropModel(
      name: "Jute",
      category: "Fiber Crop",
      growingSeason: "Kharif",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 70.0,
      humidityMax: 90.0,
      rainfallMin: 120.0,
      rainfallMax: 250.0,
      soilType: "Alluvial loam",
      waterRequirement: "High",
      emoji: "🌿",
    ),

    // --- Vegetables & Tubers ---
    CropModel(
      name: "Tomato",
      category: "Vegetable / Solanaceous",
      growingSeason: "Year-round",
      tempMin: 18.0,
      tempMax: 28.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 40.0,
      rainfallMax: 90.0,
      soilType: "Sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍅",
    ),
    CropModel(
      name: "Potato",
      category: "Tuber / Vegetable",
      growingSeason: "Rabi",
      tempMin: 16.0,
      tempMax: 24.0,
      humidityMin: 60.0,
      humidityMax: 80.0,
      rainfallMin: 50.0,
      rainfallMax: 100.0,
      soilType: "Loose friable loam",
      waterRequirement: "Moderate",
      emoji: "🥔",
    ),
    CropModel(
      name: "Pepper",
      category: "Vegetable / Solanaceous",
      growingSeason: "Summer / Kharif",
      tempMin: 20.0,
      tempMax: 30.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 40.0,
      rainfallMax: 80.0,
      soilType: "Well-drained loam",
      waterRequirement: "Moderate",
      emoji: "🫑",
    ),

    // --- Fruits & Orchards ---
    CropModel(
      name: "Apple",
      category: "Temperate Fruit",
      growingSeason: "Perennial",
      tempMin: 12.0,
      tempMax: 24.0,
      humidityMin: 55.0,
      humidityMax: 75.0,
      rainfallMin: 70.0,
      rainfallMax: 130.0,
      soilType: "Rich organic loam",
      waterRequirement: "Moderate",
      emoji: "🍎",
    ),
    CropModel(
      name: "Cherry",
      category: "Stone Fruit",
      growingSeason: "Spring-Summer",
      tempMin: 14.0,
      tempMax: 24.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 60.0,
      rainfallMax: 100.0,
      soilType: "Gravelly sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍒",
    ),
    CropModel(
      name: "Peach",
      category: "Stone Fruit",
      growingSeason: "Spring-Summer",
      tempMin: 18.0,
      tempMax: 28.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 60.0,
      rainfallMax: 110.0,
      soilType: "Deep sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍑",
    ),
    CropModel(
      name: "Grapes",
      category: "Vine Fruit",
      growingSeason: "Perennial",
      tempMin: 20.0,
      tempMax: 32.0,
      humidityMin: 45.0,
      humidityMax: 65.0,
      rainfallMin: 50.0,
      rainfallMax: 90.0,
      soilType: "Gravelly loam",
      waterRequirement: "Moderate-Low",
      emoji: "🍇",
    ),
    CropModel(
      name: "Strawberry",
      category: "Berry Fruit",
      growingSeason: "Winter / Spring",
      tempMin: 16.0,
      tempMax: 26.0,
      humidityMin: 55.0,
      humidityMax: 75.0,
      rainfallMin: 45.0,
      rainfallMax: 85.0,
      soilType: "Compost-rich sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍓",
    ),
    CropModel(
      name: "Banana",
      category: "Tropical Fruit",
      growingSeason: "Perennial",
      tempMin: 24.0,
      tempMax: 34.0,
      humidityMin: 70.0,
      humidityMax: 90.0,
      rainfallMin: 100.0,
      rainfallMax: 200.0,
      soilType: "Deep rich alluvial",
      waterRequirement: "Very High",
      emoji: "🍌",
    ),
    CropModel(
      name: "Mango",
      category: "Tropical Fruit",
      growingSeason: "Perennial",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 50.0,
      rainfallMax: 100.0,
      soilType: "Alluvial / Red loam",
      waterRequirement: "Moderate",
      emoji: "🥭",
    ),
    CropModel(
      name: "Orange",
      category: "Citrus Fruit",
      growingSeason: "Perennial",
      tempMin: 18.0,
      tempMax: 32.0,
      humidityMin: 55.0,
      humidityMax: 75.0,
      rainfallMin: 60.0,
      rainfallMax: 120.0,
      soilType: "Light loamy soil",
      waterRequirement: "Moderate",
      emoji: "🍊",
    ),
    CropModel(
      name: "Papaya",
      category: "Tropical Fruit",
      growingSeason: "Annual/Perennial",
      tempMin: 22.0,
      tempMax: 34.0,
      humidityMin: 60.0,
      humidityMax: 80.0,
      rainfallMin: 80.0,
      rainfallMax: 160.0,
      soilType: "Rich sandy loam",
      waterRequirement: "Moderate-High",
      emoji: "🍈",
    ),
    CropModel(
      name: "Pomegranate",
      category: "Subtropical Fruit",
      growingSeason: "Perennial",
      tempMin: 20.0,
      tempMax: 36.0,
      humidityMin: 40.0,
      humidityMax: 60.0,
      rainfallMin: 40.0,
      rainfallMax: 80.0,
      soilType: "Deep loam / Calcareous",
      waterRequirement: "Low-Moderate",
      emoji: "🍎",
    ),
    CropModel(
      name: "Watermelon",
      category: "Cucurbit Fruit",
      growingSeason: "Zaid (Summer)",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 45.0,
      humidityMax: 65.0,
      rainfallMin: 40.0,
      rainfallMax: 70.0,
      soilType: "Sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍉",
    ),
    CropModel(
      name: "Muskmelon",
      category: "Cucurbit Fruit",
      growingSeason: "Zaid (Summer)",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 45.0,
      humidityMax: 65.0,
      rainfallMin: 40.0,
      rainfallMax: 60.0,
      soilType: "Riverbed sandy loam",
      waterRequirement: "Moderate",
      emoji: "🍈",
    ),
    CropModel(
      name: "Coconut",
      category: "Plantation / Palm",
      growingSeason: "Perennial",
      tempMin: 25.0,
      tempMax: 35.0,
      humidityMin: 65.0,
      humidityMax: 85.0,
      rainfallMin: 100.0,
      rainfallMax: 220.0,
      soilType: "Coastal sandy loam",
      waterRequirement: "High",
      emoji: "🥥",
    ),
    CropModel(
      name: "Coffee",
      category: "Plantation / Beverage",
      growingSeason: "Perennial",
      tempMin: 18.0,
      tempMax: 28.0,
      humidityMin: 65.0,
      humidityMax: 85.0,
      rainfallMin: 120.0,
      rainfallMax: 220.0,
      soilType: "Forest volcanic loam",
      waterRequirement: "Moderate-High",
      emoji: "☕",
    ),

    // --- Pulses & Legumes ---
    CropModel(
      name: "Chickpea",
      category: "Pulse / Legume",
      growingSeason: "Rabi",
      tempMin: 15.0,
      tempMax: 25.0,
      humidityMin: 40.0,
      humidityMax: 60.0,
      rainfallMin: 30.0,
      rainfallMax: 70.0,
      soilType: "Black or sandy loam",
      waterRequirement: "Low-Moderate",
      emoji: "🥜",
    ),
    CropModel(
      name: "Kidneybeans",
      category: "Pulse / Legume",
      growingSeason: "Rabi / Kharif",
      tempMin: 15.0,
      tempMax: 25.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 60.0,
      rainfallMax: 110.0,
      soilType: "Deep organic loam",
      waterRequirement: "Moderate",
      emoji: "🫘",
    ),
    CropModel(
      name: "Pigeonpeas",
      category: "Pulse / Legume",
      growingSeason: "Kharif",
      tempMin: 20.0,
      tempMax: 32.0,
      humidityMin: 45.0,
      humidityMax: 70.0,
      rainfallMin: 60.0,
      rainfallMax: 110.0,
      soilType: "Deep vertisol loam",
      waterRequirement: "Low-Moderate",
      emoji: "🌱",
    ),
    CropModel(
      name: "Mothbeans",
      category: "Arid Pulse",
      growingSeason: "Kharif",
      tempMin: 25.0,
      tempMax: 38.0,
      humidityMin: 35.0,
      humidityMax: 55.0,
      rainfallMin: 20.0,
      rainfallMax: 60.0,
      soilType: "Sandy arid soil",
      waterRequirement: "Very Low",
      emoji: "🫘",
    ),
    CropModel(
      name: "Mungbean",
      category: "Short Pulse",
      growingSeason: "Kharif / Summer",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 40.0,
      rainfallMax: 80.0,
      soilType: "Alluvial loam",
      waterRequirement: "Low-Moderate",
      emoji: "🌱",
    ),
    CropModel(
      name: "Blackgram",
      category: "Pulse / Legume",
      growingSeason: "Kharif / Rabi",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 50.0,
      humidityMax: 75.0,
      rainfallMin: 50.0,
      rainfallMax: 90.0,
      soilType: "Deep black soil",
      waterRequirement: "Moderate",
      emoji: "🫘",
    ),
    CropModel(
      name: "Lentil",
      category: "Cool Season Pulse",
      growingSeason: "Rabi (Winter)",
      tempMin: 15.0,
      tempMax: 25.0,
      humidityMin: 45.0,
      humidityMax: 65.0,
      rainfallMin: 30.0,
      rainfallMax: 70.0,
      soilType: "Loamy alluvial",
      waterRequirement: "Low",
      emoji: "🥣",
    ),

    // --- Cash & Commercial ---
    CropModel(
      name: "Cotton",
      category: "Fiber / Cash",
      growingSeason: "Kharif",
      tempMin: 21.0,
      tempMax: 32.0,
      humidityMin: 50.0,
      humidityMax: 70.0,
      rainfallMin: 50.0,
      rainfallMax: 110.0,
      soilType: "Deep black soil",
      waterRequirement: "Moderate",
      emoji: "🌱",
    ),
    CropModel(
      name: "Sugarcane",
      category: "Cash / Commercial",
      growingSeason: "Annual",
      tempMin: 24.0,
      tempMax: 35.0,
      humidityMin: 65.0,
      humidityMax: 85.0,
      rainfallMin: 100.0,
      rainfallMax: 200.0,
      soilType: "Rich heavy loam",
      waterRequirement: "Very High",
      emoji: "🎋",
    ),
  ];
}
